-- samo-radio devices: headless Samo players wired into a physical audio output.
--
-- A device is a small daemon (github.com/bouliehaan/samo-radio) running on a
-- machine with a sound card — in the normal case, this same box, feeding its
-- line-out. Samo is the only thing that talks to it: clients send "play this
-- there" to Samo, and Samo forwards the command over the device's local
-- control API. That keeps accounts, tokens and the public tunnel in exactly one
-- place instead of growing a second half-authenticated surface on the daemon.
--
-- Two credentials point in opposite directions and both are stored here:
--   control_token — proves Samo to the device (generated by the device installer)
--   token_id      — the users.tokens row minted FOR the device so it can pull
--                   audio back out of Samo. Only the id is kept; the secret is
--                   shown once at pairing and lives on the device from then on.
--                   Deleting the device revokes it.
CREATE TABLE IF NOT EXISTS samo_radio_devices (
    id                 TEXT PRIMARY KEY,
    name               TEXT NOT NULL,
    -- Where Samo reaches the device's control API, e.g. http://127.0.0.1:7970.
    base_url           TEXT NOT NULL,
    control_token      TEXT NOT NULL DEFAULT '',
    -- Where the DEVICE reaches Samo to pull audio. Deliberately separate from
    -- whatever host a client's request arrived on: a phone on the far side of a
    -- Cloudflare tunnel must not cause the device sitting next to the server to
    -- pull its audio back through that tunnel.
    stream_base_url    TEXT NOT NULL DEFAULT '',
    token_id           TEXT NOT NULL DEFAULT '',
    -- The user whose token the device carries, so revocation can find it.
    token_user_id      TEXT NOT NULL DEFAULT '',
    enabled            BOOLEAN NOT NULL DEFAULT TRUE,
    last_seen_at       TEXT NOT NULL DEFAULT '',
    last_error         TEXT NOT NULL DEFAULT '',
    created_at         TEXT NOT NULL,
    updated_at         TEXT NOT NULL
);

-- The device list is read on every dashboard load and every client that offers
-- an output picker; keep it cheap and ordered the way it is displayed.
CREATE INDEX IF NOT EXISTS idx_samo_radio_devices_name ON samo_radio_devices (name);
