-- ListenBrainz scrobbling.
--
-- Structurally this mirrors what 0009 rebuilt Last.fm into — measured plays,
-- an idempotency ledger, and a durable write-ahead queue — because the hard
-- lessons in that migration are not Last.fm-specific: a listen must be earned
-- by audio that advanced, and it must be durable before the network is
-- touched. The listen engine itself is now shared code (internal/scrobble),
-- so these tables are the same shape by construction rather than by accident.
--
-- What differs is authentication and reach:
--
--   * ListenBrainz has no application-level key or OAuth handshake. Each user
--     pastes a personal token from their settings page, so there is no
--     listenbrainz_app_config analogue — a user row IS the whole connection.
--   * api_root is stored per user so one server can feed listenbrainz.org for
--     one listener and a self-hosted or compatible instance for another.
--   * ListenBrainz accepts historical listens, so unlike Last.fm nothing here
--     needs a two-week drop rule; the queue keeps retrying.

CREATE TABLE IF NOT EXISTS listenbrainz_user_settings (
    user_id      TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    username     TEXT        NOT NULL DEFAULT '',
    user_token   TEXT        NOT NULL,
    -- Empty means "whatever the server's default root is", so changing the
    -- default does not strand users who never chose one.
    api_root     TEXT        NOT NULL DEFAULT '',
    connected_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Measured listening, one row per (user, track) play in progress.
CREATE TABLE IF NOT EXISTS listenbrainz_plays (
    user_id          TEXT   NOT NULL,
    track_id         TEXT   NOT NULL,
    play_id          TEXT   NOT NULL DEFAULT '',
    started_at       BIGINT NOT NULL DEFAULT 0,
    last_position    BIGINT NOT NULL DEFAULT 0,
    last_observed_at BIGINT NOT NULL DEFAULT 0,
    last_advance_at  BIGINT NOT NULL DEFAULT 0,
    listened_seconds BIGINT NOT NULL DEFAULT 0,
    duration_seconds BIGINT NOT NULL DEFAULT 0,
    scrobbled        BIGINT NOT NULL DEFAULT 0,
    closed           BIGINT NOT NULL DEFAULT 0,
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (user_id, track_id)
);

CREATE INDEX IF NOT EXISTS listenbrainz_plays_advance
    ON listenbrainz_plays (user_id, last_advance_at);
CREATE INDEX IF NOT EXISTS listenbrainz_plays_updated
    ON listenbrainz_plays (updated_at);

-- One "playing now" per user; ListenBrainz models it the same way Last.fm
-- does, so the same prefetch suppression applies.
CREATE TABLE IF NOT EXISTS listenbrainz_now_playing (
    user_id    TEXT PRIMARY KEY,
    track_id   TEXT   NOT NULL DEFAULT '',
    play_id    TEXT   NOT NULL DEFAULT '',
    sent_at    BIGINT NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Idempotency ledger: claimed in the same transaction that writes the queue
-- row, so exactly one caller ever owns a given listen.
CREATE TABLE IF NOT EXISTS listenbrainz_listen_ledger (
    user_id    TEXT   NOT NULL,
    dedupe_key TEXT   NOT NULL,
    track_id   TEXT   NOT NULL DEFAULT '',
    artist     TEXT   NOT NULL DEFAULT '',
    track      TEXT   NOT NULL DEFAULT '',
    timestamp  BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (user_id, dedupe_key)
);

CREATE INDEX IF NOT EXISTS listenbrainz_listen_ledger_created
    ON listenbrainz_listen_ledger (created_at);

-- Durable write-ahead queue. Carries the full MusicBrainz identifier set,
-- because ListenBrainz — unlike Last.fm, which only takes a recording id —
-- can use every one of them to match a listen to the real recording instead
-- of guessing from the text.
CREATE TABLE IF NOT EXISTS listenbrainz_queue (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          TEXT   NOT NULL,
    kind             TEXT   NOT NULL,
    track_id         TEXT   NOT NULL DEFAULT '',
    artist           TEXT   NOT NULL DEFAULT '',
    track            TEXT   NOT NULL DEFAULT '',
    album            TEXT   NOT NULL DEFAULT '',
    album_artist     TEXT   NOT NULL DEFAULT '',
    track_number     BIGINT NOT NULL DEFAULT 0,
    duration_seconds BIGINT NOT NULL DEFAULT 0,
    played_seconds   BIGINT NOT NULL DEFAULT 0,
    timestamp        BIGINT NOT NULL DEFAULT 0,
    recording_mbid   TEXT   NOT NULL DEFAULT '',
    release_mbid     TEXT   NOT NULL DEFAULT '',
    artist_mbid      TEXT   NOT NULL DEFAULT '',
    track_mbid       TEXT   NOT NULL DEFAULT '',
    dedupe_key       TEXT   NOT NULL DEFAULT '',
    source           TEXT   NOT NULL DEFAULT '',
    attempts         BIGINT NOT NULL DEFAULT 0,
    last_error       TEXT   NOT NULL DEFAULT '',
    next_attempt_at  BIGINT NOT NULL DEFAULT 0,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS listenbrainz_queue_dedupe
    ON listenbrainz_queue (user_id, dedupe_key) WHERE dedupe_key <> '';
CREATE INDEX IF NOT EXISTS listenbrainz_queue_due
    ON listenbrainz_queue (next_attempt_at, id);
CREATE INDEX IF NOT EXISTS listenbrainz_queue_user
    ON listenbrainz_queue (user_id, created_at);

-- Audit trail of everything attempted, kept so a listener can see why a
-- listen did or did not land.
CREATE TABLE IF NOT EXISTS listenbrainz_submissions (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          TEXT   NOT NULL,
    kind             TEXT   NOT NULL,
    track_id         TEXT   NOT NULL DEFAULT '',
    artist           TEXT   NOT NULL DEFAULT '',
    track            TEXT   NOT NULL DEFAULT '',
    album            TEXT   NOT NULL DEFAULT '',
    duration_seconds BIGINT NOT NULL DEFAULT 0,
    played_seconds   BIGINT NOT NULL DEFAULT 0,
    timestamp        BIGINT NOT NULL DEFAULT 0,
    status           TEXT   NOT NULL,
    error            TEXT   NOT NULL DEFAULT '',
    source           TEXT   NOT NULL DEFAULT '',
    dedupe_key       TEXT   NOT NULL DEFAULT '',
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS listenbrainz_submissions_user
    ON listenbrainz_submissions (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS listenbrainz_submissions_created
    ON listenbrainz_submissions (created_at DESC);
